### ISSUE TITLE
Facing a problem with the orientation of the whycon tag.

### ISSUE THREAD

**Issue by damounayman** [jiriUlr/whycon-ros#2]
Hello, I am very interested in your Fiducial marker. I am trying to get the position and orientation of an object using Fiducial markers. For the position, it's perfect, but the orientation, it's wrong, there is an error of 20 to 30 deg in the Euler angle.

Can you give me a hint on where the problem is?

I use a Realsense D435i camera and the calibration settings are fed to the ROS node.

**Comment by jiriUlr** [comment]
Hi, it's hard to tell from such a brief description. Do you use WhyCon or WhyCode marker? WhyCon supports mainly position estimation. Can you provide the sample data and configuration you are using?

**Comment by damounayman** [comment]
HI, thank you for replying.
I'm using whycode marker. 
for seek of simplicity, I'm using:
 <img src="https://user-images.githubusercontent.com/67443398/182833415-f1d2337d-0a1b-4a92-9096-95a78ac03db4.png" width="100" height="100">
For the generation, I used  your  [git repo](https://github.com/jiriUlr/whycode-gen)
```bash
./whycode_gen -t 2
```
For the configuration of the launch file and ros param, I choose the following config:

- circleDiameter : 0.009 m
- numMarkers : 4 
- minSize : 30
- fieldLength : 1.0
- idBits : 2
- idSamples: 4
- hammingDist : 1
- maxPatterns : 1
- areaRatioTolerance: 40.0
- initCircularityTolerance : 100.0
- finalCircularityTolerance : 2.0
- centerDistToleranceRatio: 10
- centerDistToleranceAbs: 5.0

For the Realsense D435i  camera parameters provided by the camera_info topic, I have for 1280x720:
distortion matrix D: [0.0, 0.0, 0.0, 0.0, 0.0]
intrinsic matrix K: [908.1417846679688, 0.0, 642.3192749023438, 0.0, 908.0018310546875, 369.9261169433594, 0.0, 0.0, 1.0]

When I run the code with this config, I get these results:
![demo_whycode](https://user-images.githubusercontent.com/67443398/182840359-a37db092-f6eb-46df-8449-61716eb9be7e.gif)

```
header: 
  seq: 29707
  stamp: 
    secs: 1659613973
    nsecs: 983729336
  frame_id: "camera_color_optical_frame"
markers: 
  - 
    id: 1
    size: 1077
    u: 640.9136352539062
    v: 310.3704833984375
    angle: 2.3525354862213135
    position: 
      position: 
        x: 0.21919476985931396
        y: 0.0003418896230868995
        z: 0.014386740513145924
      orientation: 
        x: 0.9554481506347656
        y: 0.0019961483776569366
        z: -0.05576407164335251
        w: 0.28983646631240845
    rotation: 
      x: 2.5509862899780273
      y: 0.10792586952447891
      z: -0.028681274503469467
```
